query DeliveryInput {
  shop {
    goals: metafield(namespace: "zuper_threshold", key: "goals") {
      value
      type
    }
  }
  cart {
    cost {
      subtotalAmount {
        amount
      }
    }
    deliveryGroups {
      id
    }
    lines {
      id
      cost {
        subtotalAmount {
          amount
        }
      }
      quantity
      merchandise {
        ... on ProductVariant {
          product {
            id
          }
        }
      }
    }
  }
  discount {
    discountClasses
  }
}
